info:
  name: Update index settings
  type: http
  seq: 6

http:
  method: PATCH
  url: "{{MEILISEARCH_URL}}/indexes/:indexName/settings"
  params:
    - name: indexName
      value: "{{indexName}}"
      type: path
  body:
    type: json
    data: |-
      {
        "filterableAttributes": ["imdbId"]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: true
